/**
 * ================================================================
 * RAG from Scratch
 * Step 5 Verification Script - Cosine Similarity
 * ================================================================
 *
 * Purpose
 * -------
 * Verify cosine similarity at two levels:
 *
 *   Part A: controlled mathematical vectors
 *   Part B: semantic embeddings generated by Step 4
 *
 * Requirements for Part B:
 *   backend/.env contains HF_API_KEY.
 *
 * Run:
 *   npm run test:step5
 * ================================================================
 */

import 'dotenv/config';

import {
  EMBEDDING_MODEL,
  cosineSimilarity,
  embedText,
} from './pipeline.js';

const EPSILON = 1e-12;

function printDivider(title) {
  console.log('\n' + '='.repeat(80));
  console.log(title);
  console.log('='.repeat(80));
}

function assertApprox(
  actual,
  expected,
  label,
) {
  if (
    Math.abs(actual - expected) >
    EPSILON
  ) {
    throw new Error(
      `${label}: expected ${expected}, received ${actual}.`,
    );
  }

  console.log(
    `PASS - ${label}: ${actual.toFixed(6)}`,
  );
}

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

function expectFailure(label, fn) {
  try {
    fn();
    throw new Error(
      `${label}: expected an error, but none was thrown.`,
    );
  } catch (error) {
    if (
      error instanceof Error &&
      error.message.includes(
        'expected an error',
      )
    ) {
      throw error;
    }

    console.log(
      `PASS - ${label}: ${error.message}`,
    );
  }
}

function printScore(label, score) {
  console.log(
    `${label.padEnd(34)} ${score.toFixed(6)}`,
  );
}

try {
  printDivider(
    'STEP 5 - COSINE SIMILARITY TEST',
  );

  printDivider(
    'PART A - CONTROLLED VECTOR GEOMETRY',
  );

  const xAxis = [1, 0];
  const sameDirection = [2, 0];
  const yAxis = [0, 1];
  const oppositeDirection = [-3, 0];
  const diagonal = [1, 1];

  assertApprox(
    cosineSimilarity(
      xAxis,
      sameDirection,
    ),
    1,
    'same direction',
  );

  assertApprox(
    cosineSimilarity(
      xAxis,
      yAxis,
    ),
    0,
    'orthogonal vectors',
  );

  assertApprox(
    cosineSimilarity(
      xAxis,
      oppositeDirection,
    ),
    -1,
    'opposite direction',
  );

  assertApprox(
    cosineSimilarity(
      xAxis,
      diagonal,
    ),
    1 / Math.sqrt(2),
    '45-degree comparison',
  );

  const symmetryAB =
    cosineSimilarity(
      [2, 3, 4],
      [7, 8, 9],
    );

  const symmetryBA =
    cosineSimilarity(
      [7, 8, 9],
      [2, 3, 4],
    );

  assertApprox(
    symmetryAB,
    symmetryBA,
    'symmetry cos(a,b)=cos(b,a)',
  );

  const baseSimilarity =
    cosineSimilarity(
      [1, 2, 3],
      [4, 5, 6],
    );

  const scaledSimilarity =
    cosineSimilarity(
      [10, 20, 30],
      [4, 5, 6],
    );

  assertApprox(
    baseSimilarity,
    scaledSimilarity,
    'positive scale invariance',
  );

  printDivider(
    'PART B - VALIDATION TESTS',
  );

  expectFailure(
    'reject non-array input',
    () =>
      cosineSimilarity(
        'not-a-vector',
        [1, 2],
      ),
  );

  expectFailure(
    'reject empty vectors',
    () =>
      cosineSimilarity(
        [],
        [],
      ),
  );

  expectFailure(
    'reject dimension mismatch',
    () =>
      cosineSimilarity(
        [1, 2],
        [1, 2, 3],
      ),
  );

  expectFailure(
    'reject zero vector',
    () =>
      cosineSimilarity(
        [0, 0],
        [1, 2],
      ),
  );

  expectFailure(
    'reject NaN',
    () =>
      cosineSimilarity(
        [1, Number.NaN],
        [1, 2],
      ),
  );

  printDivider(
    'PART C - SEMANTIC EMBEDDING EXPERIMENT',
  );

  if (
    typeof process.env.HF_API_KEY !==
      'string' ||
    process.env.HF_API_KEY.trim() ===
      ''
  ) {
    throw new Error(
      'HF_API_KEY is required for the semantic portion of Step 5.',
    );
  }

  console.log(
    `Embedding model: ${EMBEDDING_MODEL}`,
  );

  const textA =
    'Students learn to build an end-to-end Retrieval-Augmented Generation system.';

  const textB =
    'The course teaches how to create a RAG pipeline that retrieves context for an LLM.';

  const textC =
    'Career coaching helps students prepare resumes and job applications.';

  console.log(`\nA: ${textA}`);
  console.log(`B: ${textB}`);
  console.log(`C: ${textC}`);
  console.log('\nCreating embeddings...');

  const [
    embeddingA,
    embeddingB,
    embeddingC,
  ] =
    await Promise.all([
      embedText(textA),
      embedText(textB),
      embedText(textC),
    ]);

  assert(
    embeddingA.length ===
      embeddingB.length &&
      embeddingB.length ===
      embeddingC.length,
    'Semantic embeddings must have matching dimensions.',
  );

  const similarityAB =
    cosineSimilarity(
      embeddingA,
      embeddingB,
    );

  const similarityAC =
    cosineSimilarity(
      embeddingA,
      embeddingC,
    );

  const similarityBC =
    cosineSimilarity(
      embeddingB,
      embeddingC,
    );

  printDivider(
    'SEMANTIC SIMILARITY SCORES',
  );

  printScore(
    'A vs B (both RAG-related)',
    similarityAB,
  );

  printScore(
    'A vs C (RAG vs career)',
    similarityAC,
  );

  printScore(
    'B vs C (RAG vs career)',
    similarityBC,
  );

  assert(
    similarityAB >
      similarityAC,
    'Expected the two RAG-related sentences to be more similar than RAG vs career.',
  );

  assert(
    similarityAB >
      similarityBC,
    'Expected the two RAG-related sentences to be more similar than RAG vs career.',
  );

  console.log(
    '\nPASS - semantically related RAG sentences ranked closer together.',
  );

  printDivider(
    'PART D - QUERY-STYLE DEMONSTRATION',
  );

  const query =
    'What does the program teach about retrieval-augmented generation?';

  console.log(
    `Query: ${query}`,
  );

  const queryEmbedding =
    await embedText(
      query,
    );

  const candidates = [
    {
      label: 'RAG sentence A',
      embedding: embeddingA,
    },
    {
      label: 'RAG sentence B',
      embedding: embeddingB,
    },
    {
      label: 'Career sentence C',
      embedding: embeddingC,
    },
  ];

  const ranked =
    candidates
      .map(
        (candidate) => ({
          label:
            candidate.label,
          score:
            cosineSimilarity(
              queryEmbedding,
              candidate.embedding,
            ),
        }),
      )
      .sort(
        (left, right) =>
          right.score -
          left.score,
      );

  ranked.forEach(
    (result, index) => {
      console.log(
        `${index + 1}. ${result.label.padEnd(20)} ${result.score.toFixed(6)}`,
      );
    },
  );

  assert(
    ranked[0].label !==
      'Career sentence C',
    'The career sentence should not rank first for a RAG query.',
  );

  printDivider(
    'INTERPRETATION',
  );

  console.log(
    [
      'Cosine similarity itself contains no AI and makes no API call.',
      'It is ordinary vector mathematics.',
      'The semantic behavior comes from the embedding model:',
      'the model places related text in similar directions, and cosine',
      'similarity quantifies that directional alignment.',
      'Step 6 will apply this exact calculation to stored document',
      'chunks and return the top-K highest-scoring chunks.',
    ].join(' '),
  );

  printDivider(
    'STEP 5 COMPLETE',
  );
} catch (error) {
  printDivider(
    'STEP 5 FAILED',
  );

  console.error(
    error instanceof Error
      ? error.message
      : error,
  );

  process.exitCode = 1;
}
